before_install:
    - git clone https://github.com/adamgreen/gcc4mbed.git

install: 
    - cd gcc4mbed 
    - sed -i.bak -e '108,114d;134d' linux_install
    - ./linux_install
    - ./BuildShell
    - cd ..

script:
    - make
