language: c++

before_install:
    - git clone https://github.com/adamgreen/gcc4mbed.git /tmp/gcc4mbed

install:
    - cd /tmp/gcc4mbed
    - sed -i.bak -e '108,114d;134d' linux_install
    - ./linux_install
    - cd ..
    - export PATH=$PATH:$PWD/gcc4mbed/gcc-arm-none-eabi/bin/

before_script:
    - cd /home/travis/build/UCSolarCarTeam/Schulich-Delta-CCS-Test-Tool/

script:
    - echo $PATH
    - ls /tmp/gcc4mbed/gcc-arm-none-eabi/bin
    - make
