language: c++

before_install:
    - git clone https://github.com/adamgreen/gcc4mbed.git

install: 
    - cd gcc4mbed 
    - sed -i.bak -e '108,114d;134d' linux_install
    - ./linux_install
    - cd ..

before_script:
    - echo $PWD
    - PATH=$PATH:$PWD/gcc4mbed/gcc-arm-none-eabi/bin/

script:
    - make
